'use client';
import {create} from 'zustand';
export type AppKind='computer'|'documents'|'folder'|'notepad'|'image'|'playlist'|'media-player'|'msn-contacts'|'msn-chat'|'msn-video'|'recycle'|'game'|'pinball'|'nightlog';
export interface WindowInstance{id:string;app:AppKind;title:string;x:number;y:number;width:number;height:number;minimized:boolean;maximized:boolean;z:number;resizable:boolean;payload?:Record<string,string>}
interface DesktopState{windows:Record<string,WindowInstance>;activeWindowId:string|null;selectedIconId:string|null;startMenuOpen:boolean;z:number;openWindow:(w:Omit<WindowInstance,'z'|'minimized'|'maximized'>)=>void;closeWindow:(id:string)=>void;focusWindow:(id:string)=>void;minimizeWindow:(id:string)=>void;toggleMaximize:(id:string)=>void;updateWindow:(id:string,p:Partial<WindowInstance>)=>void;selectIcon:(id:string|null)=>void;toggleStart:()=>void;closeStart:()=>void;resetWindows:()=>void;}
export const useDesktopStore=create<DesktopState>((set)=>({windows:{},activeWindowId:null,selectedIconId:null,startMenuOpen:false,z:10,
 openWindow:(w)=>set(s=>{const existing=s.windows[w.id];const z=s.z+1;return {z,activeWindowId:w.id,startMenuOpen:false,windows:{...s.windows,[w.id]:existing?{...existing,minimized:false,z,title:w.title||existing.title,payload:w.payload?{...existing.payload,...w.payload}:existing.payload}:{...w,minimized:false,maximized:false,z}}}}),
 closeWindow:id=>set(s=>{const windows={...s.windows};delete windows[id];const remaining=Object.values(windows).sort((a,b)=>b.z-a.z);return {windows,activeWindowId:remaining[0]?.id??null}}),
 focusWindow:id=>set(s=>{if(!s.windows[id])return s;const z=s.z+1;return {z,activeWindowId:id,startMenuOpen:false,windows:{...s.windows,[id]:{...s.windows[id],z,minimized:false}}}}),
 minimizeWindow:id=>set(s=>({windows:{...s.windows,[id]:{...s.windows[id],minimized:true}},activeWindowId:s.activeWindowId===id?null:s.activeWindowId})),
 toggleMaximize:id=>set(s=>({windows:{...s.windows,[id]:{...s.windows[id],maximized:!s.windows[id].maximized,minimized:false}},activeWindowId:id})),
 updateWindow:(id,p)=>set(s=>({windows:{...s.windows,[id]:{...s.windows[id],...p}}})),selectIcon:id=>set({selectedIconId:id}),toggleStart:()=>set(s=>({startMenuOpen:!s.startMenuOpen})),closeStart:()=>set({startMenuOpen:false}),resetWindows:()=>set({windows:{},activeWindowId:null,startMenuOpen:false,z:10})}));
export function openApp(app:AppKind,title?:string,payload?:Record<string,string>){const s=useDesktopStore.getState();const viewportWidth=typeof window==='undefined'?1280:window.innerWidth;const viewportHeight=typeof window==='undefined'?720:window.innerHeight;const videoWidth=Math.min(900,Math.max(520,Math.round(viewportWidth*.76)));const videoHeight=Math.min(650,Math.max(410,Math.round((viewportHeight-30)*.78)));const configs:Record<AppKind,{width:number;height:number;x:number;y:number;resizable:boolean;title:string}>={computer:{width:650,height:470,x:110,y:80,resizable:true,title:'My Computer'},documents:{width:650,height:470,x:130,y:90,resizable:true,title:'My Documents'},folder:{width:620,height:420,x:160,y:110,resizable:true,title:'Folder'},notepad:{width:620,height:440,x:175,y:100,resizable:true,title:'Notepad'},image:{width:660,height:520,x:150,y:70,resizable:true,title:'Windows Picture and Fax Viewer'},playlist:{width:350,height:360,x:520,y:115,resizable:false,title:'WINAMP PLAYLIST'},'media-player':{width:610,height:500,x:190,y:72,resizable:true,title:'Windows Media Player'},'msn-contacts':{width:300,height:565,x:682,y:66,resizable:false,title:'MSN Messenger'},'msn-chat':{width:590,height:565,x:78,y:66,resizable:true,title:'sleepless_17 - Conversation'},'msn-video':{width:videoWidth,height:videoHeight,x:Math.max(12,Math.round((viewportWidth-videoWidth)/2)),y:Math.max(12,Math.round((viewportHeight-30-videoHeight)/2)),resizable:true,title:'Video Conversation — sleepless_17'},recycle:{width:580,height:400,x:180,y:105,resizable:true,title:'Recycle Bin'},game:{width:560,height:640,x:180,y:36,resizable:false,title:'Minesweeper Flags'},pinball:{width:480,height:500,x:210,y:56,resizable:false,title:'3D Pinball for Windows - Space Cadet'},nightlog:{width:470,height:400,x:160,y:120,resizable:true,title:'Night Log'}};const c=configs[app];const id=app==='notepad'||app==='image'||app==='folder'?`${app}-${payload?.fileId||payload?.folderId||'new'}`:app==='game'?'msn-flags':app==='pinball'?'pinball':app==='media-player'?'recovered-video':app;s.openWindow({id,app,...c,title:title||c.title,payload});}
